### ISSUE TITLE
Using Digital Ocean

### ISSUE THREAD

**Issue by shashank-k** [OpenSourceBLR/java9-docker-jenkins#2]
Hi Saifi,

Other than installations, is there anything I need to do if I would be using a DO Ubuntu instance.

Regards
Shash

**Comment by saifikhan** [comment]
The workshop will encourage attendee to use stuff on their own laptops, so that they are not dependent on internet access.

Having said that, since you are knowledgeable about your Linux distro and Digital Ocean, you should be good to go !
